# Generated by Django 2.2.2 on 2019-06-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(default='DBAdmin', editable=False, max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='catalog.User')),
            ],
        ),
    ]
