# Generated by Django 2.2.2 on 2019-06-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='catalog.User')),
            ],
        ),
    ]
